sampling:
    batch_size: 256
    sampling_size: 1000
    last_only: True
    image_folder: 'sampling_image_samples'

testing:
    batch_size: 256
    sampling_size: 1000
    minisample: 1
    last_only: True
    plot_freq: 200
    n_z_samples: 100 
    n_z_samples_depart: 1 
    n_bins: 10
    compute_metric_all_steps: True
    mean_t: 0
    coverage_t: 0
    nll_t: 0
